import asyncio
import json
from functools import wraps
from mcp.client.stdio import stdio_client, StdioServerParameters
from mcp.client.session import ClientSession
import os
from app.services.context_engine import ctx_kiosk_id

# Path to the server
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SERVER_PATH = os.path.join(BASE_DIR, "mcp_server", "server.py")
PYTHON_BIN = os.path.join(BASE_DIR, "venv", "Scripts", "python.exe")

async def call_mcp_tool_async(tool_name: str, args: dict) -> str:
    server_params = StdioServerParameters(
        command=PYTHON_BIN,
        args=[SERVER_PATH],
    )
    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            result = await session.call_tool(tool_name, arguments=args)
            return result.content[0].text

def distill_payload(func):
    """
    Decorator to intercept JSON returned by FastMCP and strip unnecessary fields (Context Diet).
    """
    @wraps(func)
    async def wrapper(*args, **kwargs):
        raw_result = await func(*args, **kwargs)
        try:
            data = json.loads(raw_result)
            if isinstance(data, list):
                for item in data:
                    item.pop('created_at', None)
                    item.pop('updated_at', None)
                    item.pop('category_id', None)
                return json.dumps(data)
            return raw_result
        except json.JSONDecodeError:
            return raw_result
    return wrapper

# Define the python wrapper functions for Gemini to inspect and call

@distill_payload
async def get_print_status(transaction_id: str) -> str:
    """
    Retrieve the status and details of a specific print transaction.
    Use this when a customer asks about their print job status, charges, or document name.
    """
    return await call_mcp_tool_async("get_print_status", {"transaction_id": transaction_id})

@distill_payload
async def admin_get_kiosk_revenue() -> str:
    """
    Calculate the total revenue generated by the CURRENT printing kiosk.
    Use this when an admin asks for earnings for the machine they are standing at.
    """
    # Implicit State Injection! Gemini doesn't ask the user for kiosk_id.
    kiosk_id = ctx_kiosk_id.get()
    if not kiosk_id:
        return json.dumps({"error": "No kiosk context provided by the hardware."})
    return await call_mcp_tool_async("admin_get_kiosk_revenue", {"kiosk_id": kiosk_id})

@distill_payload
async def search_faqs(keyword: str = "") -> str:
    """
    Search for frequently asked questions (FAQs) about the printing services.
    Use this when a user asks general questions about payment methods or kiosk operations.
    """
    return await call_mcp_tool_async("search_faqs", {"keyword": keyword})

@distill_payload
async def get_categories() -> str:
    """
    Retrieve the list of product and service categories available.
    Use this to see what kinds of products or services are offered.
    """
    return await call_mcp_tool_async("get_categories", {})

@distill_payload
async def get_products(category_name: str = "") -> str:
    """
    Retrieve products available for purchase.
    Use this to get prices and descriptions of items like A4 prints, pens, cables.
    """
    return await call_mcp_tool_async("get_products", {"category_name": category_name})

# List of tools to pass to Groq (OpenAI format)
GROQ_TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "get_print_status",
            "description": "Retrieve the status and details of a specific print transaction. Use this when a customer asks about their print job status, charges, or document name.",
            "parameters": {
                "type": "object",
                "properties": {
                    "transaction_id": {
                        "type": "string",
                        "description": "The ID of the transaction to look up."
                    }
                },
                "required": ["transaction_id"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "admin_get_kiosk_revenue",
            "description": "Calculate the total revenue generated by the CURRENT printing kiosk. Use this when an admin asks for earnings for the machine they are standing at.",
            "parameters": {
                "type": "object",
                "properties": {}
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "search_faqs",
            "description": "Retrieve all frequently asked questions (FAQs). Do NOT use this tool for Corporate Policies, Shipping, or Company Info—those are in your KNOWLEDGE BASE.",
            "parameters": {
                "type": "object",
                "properties": {}
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_categories",
            "description": "Retrieve the list of product and service categories available. Use this to see what kinds of products or services are offered.",
            "parameters": {
                "type": "object",
                "properties": {}
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_products",
            "description": "Retrieve consumable products available for purchase from the database. ONLY use this for small items like A4 prints, pens, and cables. DO NOT use this for Hardware Kiosks (PRD-* IDs) - look in your KNOWLEDGE BASE for hardware instead.",
            "parameters": {
                "type": "object",
                "properties": {
                    "category_name": {
                        "type": "string",
                        "description": "The name of the category to filter products by. If you want to search all products or don't know the category, you MUST pass an empty string ''."
                    }
                },
                "required": ["category_name"]
            }
        }
    }
]

TOOL_FUNCTIONS = {
    "get_print_status": get_print_status,
    "admin_get_kiosk_revenue": admin_get_kiosk_revenue,
    "search_faqs": search_faqs,
    "get_categories": get_categories,
    "get_products": get_products
}
