from mcp.server.fastmcp import FastMCP
from db import execute_query
import json

# Initialize the FastMCP server
mcp = FastMCP("Quantan Kiosk MCP Server")

@mcp.tool()
def get_print_status(transaction_id: str) -> str:
    """
    Retrieve the status and details of a specific print transaction.
    
    Use this tool when a customer asks about the status of their print job, 
    needs to know how much they were charged, or wants to confirm what document was printed.
    
    Args:
        transaction_id: The unique identifier for the print transaction (e.g., 'TXN-001'). 
                        This should be provided by the customer.
                        
    Returns:
        A JSON string containing the transaction details (document name, pages, amount, payment status) 
        or an error message if the transaction is not found.
    """
    query = "SELECT document_name, pages, amount, payment_status FROM print_transactions WHERE id = %s"
    result_json = execute_query(query, (transaction_id,))
    
    # Check if empty array returned
    try:
        result_data = json.loads(result_json)
        if isinstance(result_data, list) and len(result_data) == 0:
            return json.dumps({"error": f"No transaction found with ID: {transaction_id}"})
    except json.JSONDecodeError:
        pass
        
    return result_json

@mcp.tool()
def admin_get_kiosk_revenue(kiosk_id: str) -> str:
    """
    Calculate the total revenue generated by a specific printing kiosk.
    
    Use this tool when an administrator asks for the total earnings, sales, or revenue 
    for a particular kiosk machine. This only calculates revenue from 'Success' prints.
    
    Args:
        kiosk_id: The unique identifier for the kiosk (e.g., 'K-101').
        
    Returns:
        A JSON string containing the total revenue for the specified kiosk 
        or an error message if the query fails.
    """
    query = "SELECT SUM(amount) as total_revenue FROM print_transactions WHERE kiosk_id = %s AND payment_status = 'Success'"
    result_json = execute_query(query, (kiosk_id,))
    return result_json

@mcp.tool()
def search_faqs(keyword: str = "") -> str:
    """
    Search for frequently asked questions (FAQs) about the printing services.
    
    Use this tool when a user asks general questions about payment methods, 
    what to do if the kiosk is out of paper, or how to print.
    
    Args:
        keyword: Optional search keyword to filter the FAQs. 
        
    Returns:
        A JSON string containing matching FAQs.
    """
    if keyword:
        query = "SELECT question, answer FROM faq WHERE question LIKE %s OR answer LIKE %s"
        search_term = f"%{keyword}%"
        return execute_query(query, (search_term, search_term))
    else:
        query = "SELECT question, answer FROM faq"
        return execute_query(query)

@mcp.tool()
def get_categories() -> str:
    """
    Retrieve the list of product and service categories available.
    
    Use this tool when the user wants to know what kinds of products or services 
    are offered (e.g., Paper Services, Stationery, Accessories).
    
    Returns:
        A JSON string containing the categories.
    """
    query = "SELECT id, name, description FROM category"
    return execute_query(query)

@mcp.tool()
def get_products(category_name: str = "") -> str:
    """
    Retrieve products available for purchase.
    
    Use this tool to get the price, description, and name of items like A4 prints, 
    pens, cables, etc.
    
    Args:
        category_name: Optional category name to filter by (e.g., 'Stationery').
        
    Returns:
        A JSON string containing the products.
    """
    if category_name:
        query = '''
            SELECT p.name, p.price, p.description 
            FROM product p 
            JOIN category c ON p.category_id = c.id 
            WHERE c.name LIKE %s
        '''
        return execute_query(query, (f"%{category_name}%",))
    else:
        query = "SELECT name, price, description FROM product"
        return execute_query(query)

if __name__ == "__main__":
    # Run the server using stdio transport
    mcp.run()
